name: 'Download and Run JAR'
description: 'Downloads a JAR file from a public GitHub release and runs it.'
author: 'Your Name'
inputs:
  version_tag:
    description: 'Version tag of the release to download'
    required: true
runs:
  using: 'node20'
  main: 'dist/main.js'
