name: 'TestSpec Action'
description: 'The BDD Framework TestSpec is a GitHub Action designed to execute against feature files.'
author: 'Volodymyr Rozdolsky'
inputs:
  version:
    description: 'The version of the TestSpec release to use.'
    required: true
  plugin_type:
    description: 'Specify whether the plugin path is a directory or a file (valid values: directory, file).'
    required: true
  plugin_path:
    description: 'The path to the directory or file where TestSpec will run.'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'award'
  color: 'green'
