name: 'TestSpec Action'
description: 'Downloads a JAR file from a public GitHub release and runs it.'
author: 'Your Name'
inputs:
  version:
    description: 'Version tag of the release to download'
    required: true
  plugin_type:
    description: 'Specify if the plugin path is a directory or a file (values: directory, file)'
    required: true
  plugin_path:
    description: 'Path to the directory or file to be used with the JAR file'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'award'
  color: 'green'